### ISSUE TITLE
当前React组件包与React18有版本冲突

### ISSUE THREAD

**Issue by PrinOrange** [wangeditor-team/wangEditor#4024]
## 问题描述

在使用create-react-app创建的React 18项目中，
用npm引入editor时正常。
但是用npm引入wangEditor5的React组件包@wangeditor/editor-for-react，提示依赖项冲突。
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: myblog-cms@0.1.0
npm ERR! Found: react@18.0.0
npm ERR! node_modules/react
npm ERR!   react@"^18.0.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^17.0.2" from @wangeditor/editor-for-react@1.0.0
npm ERR! node_modules/@wangeditor/editor-for-react
npm ERR!   @wangeditor/editor-for-react@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\PrinOrange\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\PrinOrange\AppData\Local\npm-cache\_logs\2022-04-13T03_39_11_033Z-debug.log
```
个人初步判断，是这个@wangeditor/editor-for-react组件包有React17的依赖项，导致在React18项目中发生冲突。
现今React 18已经发布，使用create-react-app创建React项目版本不再是默认的React 17
，而是React 18。React组件包和最新React项目在版本上有滞后。
## wangEditor 版本

@wangeditor/editor版本：*5.0.0*
@wangeditor/editor-for-react版本：*1.0.0*

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是*

## 最小成本的复现步骤
按照文档所说步骤即可。[https://www.wangeditor.com/v5/installation.html#npm]
- 步骤一：创建一个空目录
- 步骤二：在空目录下使用create-react-app创建一个react项目 `create-react-app test-app`
- 步骤三：在该react项目中首先引入editor：`npm install @wangeditor/editor --save`，然后引入React组件包`npm install @wangeditor/editor-for-react --save`

**Comment by hahaaha** [comment]
@PrinOrange 麻烦重新安装下@wangeditor/editor-for-react最新版本 1.0.1 应该就能解决这个问题了

**Comment by PrinOrange** [comment]
@hahaaha 感谢，安装的问题解决了，但是使用升级后的包，又出现了一些新的问题：
在React 18的空白项目中引入wangEditor5.0和@wangeditor/editor-for-react@v1.0.1后，
按照官方文档所说的步骤[[引入React组件](https://www.wangeditor.com/v5/for-frame.html#%E4%BD%BF%E7%94%A8-2)](https://www.wangeditor.com/v5/for-frame.html#%E4%BD%BF%E7%94%A8-2) 后，发生渲染错误。
**复现步骤：**

- 创建React18空白项目`create-react-app test-app --template typescript`
  
- 分别安装wangEditor和React组件包：`npm install @wangeditor/editor-for-react` `npm install @wangeditor/editor`
  
- 按照官方文档的React组件使用教程[[引入React组件](https://www.wangeditor.com/v5/for-frame.html#%E4%BD%BF%E7%94%A8-2)](https://www.wangeditor.com/v5/for-frame.html#%E4%BD%BF%E7%94%A8-2)
  
  运行后，展示白屏，并在Chrome控制台中的具体报错信息如下：
  

```
index.esm.js:17432 Uncaught Error: Repeated create editor by selector '[object HTMLDivElement]'
    at Xd (index.esm.js:17432:1)
    at createEditor (index.esm.js:19818:1)
    at Editor.tsx:97:1
    at commitHookEffectListMount (react-dom.development.js:22969:1)
    at invokePassiveEffectMountInDEV (react-dom.development.js:24948:1)
    at invokeEffectsInDev (react-dom.development.js:27142:1)
    at commitDoubleInvokeEffectsInDEV (react-dom.development.js:27121:1)
    at flushPassiveEffectsImpl (react-dom.development.js:26865:1)
    at flushPassiveEffects (react-dom.development.js:26801:1)
    at react-dom.development.js:26597:1

react-dom.development.js:18525 The above error occurred in the <f> component:
    at f (http://localhost:3000/static/js/bundle.js:660:13)
    at div
    at div
    at ArticleEditor (http://localhost:3000/static/js/bundle.js:190:78)
    at div
    at App

index.esm.js:17432 Uncaught Error: Repeated create editor by selector '[object HTMLDivElement]'
    at Xd (index.esm.js:17432:1)
    at createEditor (index.esm.js:19818:1)
    at Editor.tsx:97:1
    at commitHookEffectListMount (react-dom.development.js:22969:1)
    at invokePassiveEffectMountInDEV (react-dom.development.js:24948:1)
    at invokeEffectsInDev (react-dom.development.js:27142:1)
    at commitDoubleInvokeEffectsInDEV (react-dom.development.js:27121:1)
    at flushPassiveEffectsImpl (react-dom.development.js:26865:1)
    at flushPassiveEffects (react-dom.development.js:26801:1)
    at react-dom.development.js:26597:1
```

由报错信息，判断发生了重复渲染问题。希望能解决，谢谢！

**Comment by hahaaha** [comment]
我这边一会看一下
