### ISSUE TITLE
vue3 demo报错

### ISSUE THREAD

**Issue by LeoliuGH** [wangeditor-team/wangEditor#4102]
按照官网demo配置完启动报错：
index.esm.js:237 Uncaught (in promise) TypeError: Object(...) is not a function
    at Proxy._sfc_render (index.esm.js:237:129)
    at renderComponentRoot (runtime-core.esm-bundler.js:1294:44)
    at componentEffect (runtime-core.esm-bundler.js:5323:57)
    at reactiveEffect (reactivity.esm-bundler.js:71:24)
    at effect (reactivity.esm-bundler.js:46:9)
    at setupRenderEffect (runtime-core.esm-bundler.js:5276:89)
    at mountComponent (runtime-core.esm-bundler.js:5235:9)
    at processComponent (runtime-core.esm-bundler.js:5193:17)
    at patch (runtime-core.esm-bundler.js:4796:21)
    at mountChildren (runtime-core.esm-bundler.js:4983:13)

**Comment by LeoliuGH** [comment]
找到问题了，升级最新的vue3版本就好了

**Comment by LeoliuGH** [comment]
npm install vue@next
