### ISSUE TITLE
按照官网视频教程‘用于vue3’，使用模板代码之后自动项目报错

### ISSUE THREAD

**Issue by zhenxichaofenle** [wangeditor-team/wangEditor#4235]
## 问题描述

*请根据官网视频教程‘用于vue3’使用模板代码之后自动项目报错,
Pre-bundling dependencies:
  vue
  moment
  moment/dist/locale/zh-cn
  @vue/apollo-composable  
  @vueuse/motion
  (...and 45 more)        
(this will be run only when your dependencies or config have changed)
 > node_modules/@wangeditor/editor-for-vue/dist/index.esm.js:20:79: error: No matching export in "node_modules/vue/dist/vue.runtime.esm-bundler.js" for import "createElementBlock"
    20 │ import { defineComponent, ref, shallowRef, onMounted, watch, toRaw, openBlock, createElementBlock, watchEffect } from "vue";
       ╵                                                                                ~~~~~~~~~~~~~~~~~~

error when starting dev server:  
Error: Build failed with 1 error:
node_modules/@wangeditor/editor-for-vue/dist/index.esm.js:20:79: error: No matching export in "node_modules/vue/dist/vue.runtime.esm-bundler.js" for import "createElementBlock"
    at failureErrorWithLog (D:\professional\gitrepo\website-next\node_modules\esbuild\lib\main.js:1449:15)
    at D:\professional\gitrepo\website-next\node_modules\esbuild\lib\main.js:1131:28
    at runOnEndCallbacks (D:\professional\gitrepo\website-next\node_modules\esbuild\lib\main.js:921:63)
    at buildResponseToResult (D:\professional\gitrepo\website-next\node_modules\esbuild\lib\main.js:1129:7)
    at D:\professional\gitrepo\website-next\node_modules\esbuild\lib\main.js:1236:14
    at D:\professional\gitrepo\website-next\node_modules\esbuild\lib\main.js:609:9
    at handleIncomingPacket (D:\professional\gitrepo\website-next\node_modules\esbuild\lib\main.js:706:9)
    at Socket.readFromStdout (D:\professional\gitrepo\website-next\node_modules\esbuild\lib\main.js:576:7)
    at Socket.emit (node:events:390:28)
    at Socket.emit [(node:domain:475:12).*]

## wangEditor 版本

*5*

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一：在已有项目中，按照视频教程‘用于vue3’
- 步骤二：启动项目npm run dev之后，就报上面的错误
- 步骤三

**Comment by wangfupeng1988** [comment]
去查看官网 demo 源码吧。
