### ISSUE TITLE
插入表格，光标移至表格前方，控制台报错

### ISSUE THREAD

**Issue by lcmomo** [wangeditor-team/wangEditor#4376]
## bug 描述

*插入表格后，将光标移至表格前方位置，控制台报错*

## 你预期的样子是？

*插入表格后，光标移至表格前方位置，控制台不报错*

## 系统和浏览器及版本号

- 操作系统
 macOs Catalina 10.15.7
- 浏览器和版本
chrome 102.0.5005.61
## wangEditor 版本

*V5.1.1*

## demo 能否复现该 bug ？

能

- 中文 demo https://www.wangeditor.com/demo/index.html
- English demo https://www.wangeditor.com/demo/?lang=en

## 在线 demo

*请尽量提供在线 demo （推荐以下网站），帮助我们最低成本复现 bug*

- https://codesandbox.io/
- https://codepen.io/
- https://stackblitz.com/

## 最小成本的复现步骤

官网demo-默认模式

- 步骤一
点击插入表格工具栏，插入m*n 列表格
- 步骤二
-移动光标至表格前方位置
- 步骤三
- 控制台报错
 Uncaught Error: Cannot resolve a Slate point from DOM point: [object HTMLDivElement],0
    at Object.toSlatePoint (index.js:21651:18333)
    at Object.toSlateRange (index.js:21651:16704)
    at index.js:21651:68674
    at HTMLDocument.<anonymous> (index.js:21651:68783)
    at invokeFunc (index.js:12654:21)
    at leadingEdge (index.js:12664:24)
    at HTMLDocument.debounced (index.js:12729:18)

**Comment by wangfupeng1988** [comment]
已在官网 demo 复现，如下图

<img width="1763" alt="image" src="https://user-images.githubusercontent.com/9583120/173785622-5f223b88-0037-40d9-a2d1-ba68cc168ddb.png">

**Comment by Nik0601** [comment]
这边也提示如上图重现的bug，具体表现为：
wangEditor.js:21651 Uncaught (in promise) Error: Cannot resolve a DOM node from Slate node: {"text":""}
    at Object.toDOMNode (wangEditor.js:21651)
    at Object.toDOMPoint (wangEditor.js:21651)
    at Object.toDOMRange (wangEditor.js:21651)
    at wangEditor.js:21651
    at wangEditor.js:21651
  ----------------------------------------------
  请问这个bug该如何修复解决？

**Comment by rhydian0x** [comment]
开源作者大佬是不是忘记了还有这个问题，很致命🤔

**Comment by Yalonexm** [comment]
此问题在编辑时， 双击空行 `<p><br></p>` 100%复现

**Comment by xenera-wangrui** [comment]
import { useEffect } from "react";

const useErrorOverlaySuppress = () => {
useEffect(() => {
const handler = (event: ErrorEvent) => {
if (
event.message?.includes("Cannot resolve a Slate point from DOM point")
) {
event.preventDefault();
const overlays = document.querySelectorAll(
"[data-nextjs-error-overlay], iframe"
);
overlays.forEach((el) => el.remove());
}
};

window.addEventListener("error", handler);
return () => {
  window.removeEventListener("error", handler);
};
}, []);
};
export default useErrorOverlaySuppress;
自定义hooks 强制阻止报错 拿去不谢
