### ISSUE TITLE
Problem using library with nextjs - ReferenceError: nodeCrypto is not defined

### ISSUE THREAD

**Issue by whydea** [wangeditor-team/wangEditor#5225]
When using the lib with NextJS, the error "ReferenceError: nodeCrypto is not defined."
This error is happening in server side rendering.
From what I identified, the nodepolyfill.ts file is using the crypto lib, but apparently it is not being imported.
I am using NextJS version 13.1.1 and node version 18.12.1

to solve this problem I did the import as follows
const RichTextEditor = dynamic(
   () => import('../../../../../components/RichTextEditor'),
   { ssr: true },
);
however, I believe that the problem should be solved so that the library also works on server side

**Comment by griffenliu** [comment]
我也碰到类似的问题，使用sveltekit的时候，一开始能正常加载和使用，刷新几次就报这个错误了：
ReferenceError: nodeCrypto is not defined
    at Object.getRandomValues (E:\Workspace\Test\svelte-app2\node_modules\@wangeditor\editor\dist\index.js:71:19)
    at generate_nonce (/node_modules/@sveltejs/kit/src/runtime/server/page/csp.js:7:9)
    at Csp.<instance_members_initializer> (/node_modules/@sveltejs/kit/src/runtime/server/page/csp.js:212:10)
    at new Csp (/node_modules/@sveltejs/kit/src/runtime/server/page/csp.js:224:13)
    at Module.render_response (/node_modules/@sveltejs/kit/src/runtime/server/page/render.js:209:14)
    at async Module.respond_with_error (/node_modules/@sveltejs/kit/src/runtime/server/page/respond_with_error.js:77:10)
    at async Module.render_page (/node_modules/@sveltejs/kit/src/runtime/server/page/index.js:329:10)
    at async resolve (/node_modules/@sveltejs/kit/src/runtime/server/respond.js:369:17)
    at async Module.respond (/node_modules/@sveltejs/kit/src/runtime/server/respond.js:240:20)
    at async file:///E:/Workspace/Test/svelte-app2/node_modules/@sveltejs/kit/src/exports/vite/dev/index.js:500:22

**Comment by griffenliu** [comment]
> 

我已经解决掉了在Sveltekit中使用时的这个问题。原因是在使用node作为后端渲染时没有了这个nodeCrypto，我也不知道为啥没有。既然没有，咱就不用后端渲染了，在Sveltekit页面配置项中禁用服务端渲染即可： export const ssr=false;
