### ISSUE TITLE
HTML解析抛出异常 Text node parent is Editor 组件无法运行

### ISSUE THREAD

**Issue by axolo** [wangeditor-team/wangEditor#5635]
## bug 描述

HTML解析时，抛出异常：Text node parent is Editor，组件无法运行

## 你预期的样子是？

组件正确解析HTML并正常运行

## 系统和浏览器及版本号

- Windows 11 22H2
- Microsoft Edge 版本 115.0.1901.200 (正式版本) (64 位)

## wangEditor 版本

- @wangeditor/editor@^5.1.23
- @wangeditor/editor-for-vue@^5.1.12

## demo 能否复现该 bug ？

不能

## 在线 demo

无

## 最小成本的复现步骤

```vue
<Editor 
  ref="editor" 
  modelValue="<b>测试富文本编辑器</b>" 
/>
```

```
Uncaught (in promise) Error: Text node {"text":"测试富文本编辑器","bold":true} parent is Editor
    at index.esm.js:23:54522
    at index.esm.js:23:54759
    at Array.map (<anonymous>)
    at index.esm.js:23:54389
    at UT (index.esm.js:23:55088)
    at index.esm.js:23:55442
    at Array.map (<anonymous>)
    at WT (index.esm.js:23:55417)
    at e10.changeViewState (index.esm.js:23:73810)
    at I_ (index.esm.js:23:96278)
```

**Comment by zhchlmm** [comment]
在最外层添加p标签即可解决

**Comment by yc-lm** [comment]
使用正则来替换ul，ol,li,dl,dd,dt之间的空格

**Comment by yc-lm** [comment]
解决思路：使用正则替换ul，li等标签间的空格

![正则](https://github.com/user-attachments/assets/a90308c2-52fd-417f-a364-044f2c66fdc0)
function removeSpacesBetweenSpecial(html) {
html = html.replace(REGEX_RULE.UL_LI_SPACE, '');
html = html.replace(REGEX_RULE.OL_LI_SPACE, '');
html = html.replace(REGEX_RULE.DL_DT_SPACE, '');
html = html.replace(REGEX_RULE.DL_DD_SPACE, '');
return html;
}`
