### ISSUE TITLE
vue 集成wangeditor 插入表格是点击表格旁边出现错误

### ISSUE THREAD

**Issue by yomansunterweb** [wangeditor-team/wangEditor#5802]
Cannot resolve a Slate point from DOM point: [object HTMLDivElement],0
    at Object.toSlatePoint (http://localhost:8080/static/wEditor/index.js:21658:7)
    at Object.toSlateRange (http://localhost:8080/static/wEditor/index.js:21657:16704)
    at http://localhost:8080/static/wEditor/index.js:21659:55395
    at HTMLDocument.<anonymous> (http://localhost:8080/static/wEditor/index.js:21659:55504)
    at invokeFunc (http://localhost:8080/static/wEditor/index.js:12660:21)
    at leadingEdge (http://localhost:8080/static/wEditor/index.js:12670:24)
    at HTMLDocument.debounced (http://localhost:8080/static/wEditor/index.js:12735:18)

**Comment by yomansunterweb** [comment]
这个问题搜索了一下好像提问至少8遍左右，一直没有界面，看了一下源代码，过于复杂

**Comment by yomansunterweb** [comment]
这个问题搜索了一下好像提问至少8遍左右，一直没有解决，看了一下源代码，过于复杂

**Comment by yomansunterweb** [comment]
但是仔细问题跟踪 后面是t.parentElement 为空  估计  t就是table   因为用的是slate.js压缩版本，花了点时间看了看，解决这个问题估计要判断t.parentment ！=null   才能赋值， 修改后也是一大推问题了，让作者弄弄，毕竟他最熟悉

**Comment by yomansunterweb** [comment]
通过slate.js来开发都工作量非常大，不感考虑完全自己开发是什么情况

**Comment by end-cycle** [comment]
#5829 
作者现在在搞[划水AI](https://huashuiai.com/)了,毕竟要赚钱，没时间维护这个项目。

**Comment by cycleccc** [comment]
#5830 上次的pr后面测出了bug，这次的应该更符合设计原则

**Comment by xenera-wangrui** [comment]
import { useEffect } from "react";

const useErrorOverlaySuppress = () => {
useEffect(() => {
const handler = (event: ErrorEvent) => {
if (
event.message?.includes("Cannot resolve a Slate point from DOM point")
) {
event.preventDefault();
const overlays = document.querySelectorAll(
"[data-nextjs-error-overlay], iframe"
);
overlays.forEach((el) => el.remove());
}
};

window.addEventListener("error", handler);
return () => {
  window.removeEventListener("error", handler);
};
}, []);
};
export default useErrorOverlaySuppress;
自定义hooks 强制阻止报错 拿去不谢
