### ISSUE TITLE
打开官网demo一样的问题 插入table 

### ISSUE THREAD

**Issue by yomansunterweb** [wangeditor-team/wangEditor#5804]
index.js:21657 Uncaught Error: Cannot resolve a Slate point from DOM point: [object HTMLDivElement],0
    at Object.toSlatePoint (index.js:21657:18333)
    at Object.toSlateRange (index.js:21657:16704)
    at index.js:21657:73785
    at HTMLDocument.<anonymous> (index.js:21657:73894)
    at invokeFunc (index.js:12660:21)
    at leadingEdge (index.js:12670:24)
    at HTMLDocument.debounced (index.js:12735:18)
toSlatePoint @ index.js:21657
toSlateRange @ index.js:21657
(anonymous) @ index.js:21657
(anonymous) @ index.js:21657
invokeFunc @ index.js:12660
leadingEdge @ index.js:12670
debounced @ index.js:12735
4de

demo 是网页版直接在后台抛出了，但是vue不同，会把错误弹出来

**Comment by xenera-wangrui** [comment]
import { useEffect } from "react";

const useErrorOverlaySuppress = () => {
  useEffect(() => {
    const handler = (event: ErrorEvent) => {
      if (
        event.message?.includes("Cannot resolve a Slate point from DOM point")
      ) {
        event.preventDefault();
        const overlays = document.querySelectorAll(
          "[data-nextjs-error-overlay], iframe"
        );
        overlays.forEach((el) => el.remove());
      }
    };

    window.addEventListener("error", handler);
    return () => {
      window.removeEventListener("error", handler);
    };
  }, []);
};
export default useErrorOverlaySuppress;
  自定义hooks  强制阻止报错 拿去不谢
