### ISSUE TITLE
mvc模式用了js和vue js 但是就是显示不出来报错

### ISSUE THREAD

**Issue by xcjcai** [wangeditor-team/wangEditor#5843]
<script src="~/Scripts/layui/layui.js"></script> <script src="~/Scripts/element-plus/ElementPlusIconsVue.js"></script> <script src="~/Scripts/jquery-3.3.1.min.js"></script> <script src="~/Scripts/element-plus/zh-cn.js"></script> <script src="~/Scripts/element-plus/element.js"></script> <script src="~/Scripts/wangEditor/index.js"></script> <script src="~/Scripts/Home/Work.js"></script> <script src="~/Scripts/Home/WorkTask.js"></script>先导入这些文件
workjs的代码
var vueapp = Vue.createApp({
//el: "#vue",
data() {
return {
editor: null,
editorContent: '',
drawer: false,//抽屉
isQueryZJ: 1,//0-不查询数据库质检任务，1-查询数据库质检任务
outside: null,//'历史表或者实时表'
taskIDForZJ: 0, // 个人中心传入的任务ID
iTypeForZJ: 0, //个人中心那边 传过来的状态 1-显示、2-修改、3-返工
iSourceTypeZJ: 2,// 1-工作台打开的质检任务 2-个人中心打开的质检任务
getTaskWorkForZJ: "/WebApi/GetTaskWorkForJZ",
submitForZJ: "/WebApi/SubmitForZJ",
taskInfoForZJ: {

},
detailsurl: "Home",
get: "/WebApi/GetUserSkill",
getProject: "/WebApi/GetProjectList",
getTask: "/WebApi/GetTaskWorkList",
returnTaskWork: "/WebApi/ReturnTaskWork",
suspendTask: "/WebApi/SuspendTask",
suspendTaskZJ: "/WebApi/SuspendTaskForZJ",
refreshSession: "/WebApi/RefreshSession",
getTimeSpan: "/WebApi/GetTimeSpan",
setUserWorking: "/WebApi/SetUserWorking",
p: {},
userFinishCount: 0,
isWork: true,
btnText: "停止工作",
selectedItem: [],
selectedItemSkill: [],
items: {
skill: {},
project: {},
taskInfo: {
discoName: "曲靖生产中心",
//projectName: "深圳证券",
//taskName: "高管信息录入",
//price: "1.50元/PDF",
sjbName: "", taskID: ""
},
},
selectedProject: [],
selectedProID: [],
project: {},
taskInfo: {
SoftwareURL: "任务申请中..."//"[http://192.168.10.216:10001/twjd/Homes/Index?T=1001&iID=7"+"&vl=1.0.2.0](http://192.168.10.216:10001/twjd/Homes/Index?T=1001&iID=7%22+%22&vl=1.0.2.0)"
},
windowTem: null,
setID: null,
TimeSpan: null, //客户端与服务器时间差
AssignTimeForDisplay: null //客户端显示申请时间
}
},
mounted: function () {

    this.editor =wangEditor(document.getElementById("aaac"));
    this.editor.customConfig.onchange = (html) => {
        this.editorContent = html;
    };
    this.editor.create();
    // 或者 const editor = new E( document.getElementById('div1') )
    var vm = this;
  
    //vm.SetTimeOutZJ();
    layui.use(["layer"], function () {
        vm.layer = layui.layer;
    });
    if (vm.taskIDForZJ != null && vm.iTypeForZJ != null) {
        vm.InitParamForZJ();
    }
    else {
        vm.InitParam();
    }

},
})

for（[name，comp] of Object.entries（ElementPlusIconsVue））{
vueapp.component（name，comp）;
}
vueapp.use（ElementPlus，{
locale：ElementPlusLocaleZhCn，
}）;

vueapp.mount("#vue");就是这样子引用的可是无论我怎么写都报错
前端报错显示
Uncaught TypeError: wangEditor is not a constructor
at Proxy.mounted (Work.js:63:23)
at vue.js:4117:94
at callWithErrorHandling (vue.js:1631:26)
at callWithAsyncErrorHandling (vue.js:1639:25)
at hook.__weh.hook.__weh (vue.js:4097:29)
at flushPostFlushCbs (vue.js:1796:51)
at render (vue.js:7739:13)
at mount (vue.js:5262:29)
at app.mount (vue.js:10471:27)
at Work.js:1215:8

front-end code

**Comment by cycleccc** [comment]
这和wangEditor没关系吧，看起来是你引入wangeditor与创建的问题，wangEditor从哪儿引进来当做构造函数的？，试试按照文档教程来创建
