### ISSUE TITLE
富文本设置时报错

### ISSUE THREAD

**Issue by maxin666155** [wangeditor-team/wangEditor#5979]
## bug 描述
下面这个node找不到后代 at path 4
    at Object.get (index.js:5081:17)
    at Object.levels (index.js:5185:26)
    at levels.next (<anonymous>)
    at Object.n (index.js:3290:777)
    at Object.levels (index.js:3708:52)
    at levels.next (<anonymous>)
    at Object.n (index.js:3290:777)
    at Object.above (index.js:3326:49)
    at Object._void [as void] (index.js:4763:21)
    at index.js:8655:37*

{
    "children": [
        {
            "type": "paragraph",
            "children": [
                {
                    "text": ""
                }
            ]
        }
    ],
    "operations": [],
    "selection": {
        "anchor": {
            "path": [
                4,
                0
            ],
            "offset": 22
        },
        "focus": {
            "path": [
                4,
                0
            ],
            "offset": 22
        }
    },
    "marks": null,
    "id": "wangEditor-1",
    "isDestroyed": false,
    "isFullScreen": false,
    "history": {
        "undos": [
            [
                {
                    "type": "remove_node",
                    "path": [
                        0
                    ],
                    "node": {
                        "type": "paragraph",
                        "children": [
                            {
                                "text": ""
                            }
                        ]
                    }
                },
                {
                    "type": "insert_node",
                    "path": [
                        0
                    ],
                    "node": {
                        "type": "paragraph",
                        "children": [
                            {
                                "text": ""
                            }
                        ]
                    }
                },
                {
                    "type": "remove_node",
                    "path": [
                        0
                    ],
                    "node": {
                        "type": "paragraph",
                        "children": [
                            {
                                "text": ""
                            }
                        ]
                    }
                },
                {
                    "type": "insert_node",
                    "path": [
                        0
                    ],
                    "node": {
                        "type": "header1",
                        "children": [
                            {
                                "text": "如何在‌VSCode中设置自动换行‌"
                            }
                        ]
                    }
                },
                {
                    "type": "insert_node",
                    "path": [
                        1
                    ],
                    "node": {
                        "type": "paragraph",
                        "children": [
                            {
                                "text": "打开VSCode后，点击左下角的齿轮图标或使用快捷键Ctrl+,(Windows/Linux)或Cmd+,(macOS)访问设置。"
                            }
                        ]
                    }
                },
                {
                    "type": "insert_node",
                    "path": [
                        2
                    ],
                    "node": {
                        "type": "paragraph",
                        "children": [
                            {
                                "text": "在设置面板中，使用搜索框输入“‌Word Wrap”来快速找到相关选项。"
                            }
                        ]
                    }
                },
                {
                    "type": "insert_node",
                    "path": [
                        3
                    ],
                    "node": {
                        "type": "paragraph",
                        "children": [
                            {
                                "text": "在“Word Wrap”选项下，选择适合您的阅读和编码习惯的模式："
                            }
                        ]
                    }
                },
                {
                    "type": "insert_node",
                    "path": [
                        4
                    ],
                    "node": {
                        "type": "paragraph",
                        "children": [
                            {
                                "text": "‌off‌：关闭自动换行，文本不会自动换行。"
                            }
                        ]
                    }
                },
                {
                    "type": "insert_node",
                    "path": [
                        5
                    ],
                    "node": {
                        "type": "paragraph",
                        "children": [
                            {
                                "text": "‌on‌：启用自动换行，当文本达到编辑器宽度时会换行。"
                            }
                        ]
                    }
                },
                {
                    "type": "insert_node",
                    "path": [
                        6
                    ],
                    "node": {
                        "type": "paragraph",
                        "children": [
                            {
                                "text": "‌wordWrapColumn‌：在指定列数的位置启用自动换行。"
                            }
                        ]
                    }
                },
                {
                    "type": "insert_node",
                    "path": [
                        7
                    ],
                    "node": {
                        "type": "paragraph",
                        "children": [
                            {
                                "text": "‌bounded‌：当行长度超过最小视图宽度和指定列数时自动换行。"
                            }
                        ]
                    }
                },
                {
                    "type": "insert_node",
                    "path": [
                        8
                    ],
                    "node": {
                        "type": "paragraph",
                        "children": [
                            {
                                "text": "不同自动换行模式的使用场景"
                            }
                        ]
                    }
                },
                {
                    "type": "insert_node",
                    "path": [
                        9
                    ],
                    "node": {
                        "type": "paragraph",
                        "children": [
                            {
                                "text": "‌off‌：适用于需要查看非常长的行时，避免不必要的换行。"
                            }
                        ]
                    }
                },
                {
                    "type": "insert_node",
                    "path": [
                        10
                    ],
                    "node": {
                        "type": "paragraph",
                        "children": [
                            {
                                "text": "‌on‌：适合大多数情况，文本会在编辑器宽度达到时自动换行。"
                            }
                        ]
                    }
                },
                {
                    "type": "insert_node",
                    "path": [
                        11
                    ],
                    "node": {
                        "type": "paragraph",
                        "children": [
                            {
                                "text": "‌wordWrapColumn‌：适合需要精确控制换行位置的用户，可以指定特定列数（如80列）来强制换行。"
                            }
                        ]
                    }
                },
                {
                    "type": "insert_node",
                    "path": [
                        12
                    ],
                    "node": {
                        "type": "paragraph",
                        "children": [
                            {
                                "text": "‌bounded‌：适合需要在不同大小的视窗中展示文本的情况，确保文本在视图内完整展示。"
                            }
                        ]
                    }
                },
                {
                    "type": "remove_text",
                    "path": [
                        0,
                        0
                    ],
                    "offset": 0,
                    "text": "如何在‌VSCode中设置自动换行‌"
                },
                {
                    "type": "remove_node",
                    "path": [
                        1
                    ],
                    "node": {
                        "type": "paragraph",
                        "children": [
                            {
                                "text": "打开VSCode后，点击左下角的齿轮图标或使用快捷键Ctrl+,(Windows/Linux)或Cmd+,(macOS)访问设置。"
                            }
                        ]
                    }
                },
                {
                    "type": "remove_node",
                    "path": [
                        1
                    ],
                    "node": {
                        "type": "paragraph",
                        "children": [
                            {
                                "text": "在设置面板中，使用搜索框输入“‌Word Wrap”来快速找到相关选项。"
                            }
                        ]
                    }
                },
                {
                    "type": "remove_node",
                    "path": [
                        1
                    ],
                    "node": {
                        "type": "paragraph",
                        "children": [
                            {
                                "text": "在“Word Wrap”选项下，选择适合您的阅读和编码习惯的模式："
                            }
                        ]
                    }
                },
                {
                    "type": "remove_node",
                    "path": [
                        1
                    ],
                    "node": {
                        "type": "paragraph",
                        "children": [
                            {
                                "text": "‌off‌：关闭自动换行，文本不会自动换行。"
                            }
                        ]
                    }
                },
                {
                    "type": "remove_node",
                    "path": [
                        1
                    ],
                    "node": {
                        "type": "paragraph",
                        "children": [
                            {
                                "text": "‌on‌：启用自动换行，当文本达到编辑器宽度时会换行。"
                            }
                        ]
                    }
                },
                {
                    "type": "remove_node",
                    "path": [
                        1
                    ],
                    "node": {
                        "type": "paragraph",
                        "children": [
                            {
                                "text": "‌wordWrapColumn‌：在指定列数的位置启用自动换行。"
                            }
                        ]
                    }
                },
                {
                    "type": "remove_node",
                    "path": [
                        1
                    ],
                    "node": {
                        "type": "paragraph",
                        "children": [
                            {
                                "text": "‌bounded‌：当行长度超过最小视图宽度和指定列数时自动换行。"
                            }
                        ]
                    }
                },
                {
                    "type": "remove_node",
                    "path": [
                        1
                    ],
                    "node": {
                        "type": "paragraph",
                        "children": [
                            {
                                "text": "不同自动换行模式的使用场景"
                            }
                        ]
                    }
                },
                {
                    "type": "remove_node",
                    "path": [
                        1
                    ],
                    "node": {
                        "type": "paragraph",
                        "children": [
                            {
                                "text": "‌off‌：适用于需要查看非常长的行时，避免不必要的换行。"
                            }
                        ]
                    }
                },
                {
                    "type": "remove_node",
                    "path": [
                        1
                    ],
                    "node": {
                        "type": "paragraph",
                        "children": [
                            {
                                "text": "‌on‌：适合大多数情况，文本会在编辑器宽度达到时自动换行。"
                            }
                        ]
                    }
                },
                {
                    "type": "remove_node",
                    "path": [
                        1
                    ],
                    "node": {
                        "type": "paragraph",
                        "children": [
                            {
                                "text": "‌wordWrapColumn‌：适合需要精确控制换行位置的用户，可以指定特定列数（如80列）来强制换行。"
                            }
                        ]
                    }
                },
                {
                    "type": "remove_text",
                    "path": [
                        1,
                        0
                    ],
                    "offset": 0,
                    "text": "‌bounded‌：适合需要在不同大小的视窗中展示文本的情况，确保文本在视图内完整展示。"
                },
                {
                    "type": "remove_node",
                    "path": [
                        0
                    ],
                    "node": {
                        "type": "header1",
                        "children": [
                            {
                                "text": ""
                            }
                        ]
                    }
                },
                {
                    "type": "remove_node",
                    "path": [
                        0
                    ],
                    "node": {
                        "type": "paragraph",
                        "children": [
                            {
                                "text": ""
                            }
                        ]
                    }
                },
                {
                    "type": "insert_node",
                    "path": [
                        0
                    ],
                    "node": {
                        "type": "paragraph",
                        "children": [
                            {
                                "text": ""
                            }
                        ]
                    }
                }
            ]
        ],
        "redos": []
    }
}

## 你预期的样子是？

*请输入内容……*

## 系统和浏览器及版本号

- 操作系统
- 浏览器和版本

## wangEditor 版本

*请输入内容……*

## demo 能否复现该 bug ？

能/不能

- 中文 demo https://www.wangeditor.com/demo/
- English demo https://www.wangeditor.com/demo/?lang=en

## 在线 demo

*请尽量提供在线 demo （推荐以下网站），帮助我们最低成本复现 bug*

- https://codesandbox.io/
- https://codepen.io/
- https://stackblitz.com/

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
- 步骤二
- 步骤三

**Comment by cycleccc** [comment]
有可以复现的 content、html 、或是 沙盒 demo 吗，上面的给出的信息不好定位
