### ISSUE TITLE
在Windows上搭建WebView2客户端使用wangeditor和搜狗输入法执行特定步骤会出现异常

### ISSUE THREAD

**Issue by zhkkjun** [wangeditor-team/wangEditor#5982]
## bug 描述
在Windows上使用WEBVIEW2系统组件构建WEB客户端使用搜狗输入法执行特定步骤会出现异常，并且后续无法输入文字。

## 你预期的样子是？
没有异常，并且后续可以继续输入文字

## 系统和浏览器及版本号
Windows10 22H2
Microsoft Edge WebView2
版本 129.0.2792.89 (正式版本) (64 位)

直接在Microsoft Edge中不会复现，必须使用Edge的WebView2组件

## wangEditor 版本
使用在线demo的链接，在WEB客户端DEMO中运行（2024-10-15）
https://www.wangeditor.com/demo/index.html

## demo 能否复现该 bug ？
能，WEB客户端 DEMO链接: https://pan.baidu.com/s/1gCbel4Gv63e3XCdfzl1ZkQ 提取码: pp58
也可以通过微软文档，自行构建一个WEB 客户端
https://learn.microsoft.com/zh-cn/microsoft-edge/webview2/get-started/win32

- 步骤一：输入一段任意文字，足够长的字符串，最好如动图所示
- 步骤二：全选
- 步骤三：在搜狗中文状态下输入任意字母
-

![BUG](https://github.com/user-attachments/assets/ee749f89-04f2-4631-81bd-e0fd2b32ad89)

**Comment by zhkkjun** [comment]
Uncaught Error: Cannot resolve a Slate node from DOM node: [object HTMLSpanElement]
    at Object.toSlateNode (index.js:21657:15251)
    at Object.toSlatePoint (index.js:21657:18403)
    at Object.toSlateRange (index.js:21657:16704)
    at index.js:21657:73785
    at HTMLDocument.<anonymous> (index.js:21657:73894)
    at invokeFunc (index.js:12660:21)
    at HTMLDocument.debounced (index.js:12740:18)
2index.js:12961  Uncaught (in promise) NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at Object.removeChild (index.js:12961:12)
    at removeVnodes (index.js:13201:27)
    at patchVnode (index.js:13322:19)
    at updateChildren (index.js:13233:19)
    at patchVnode (index.js:13306:23)
    at updateChildren (index.js:13233:19)
    at patchVnode (index.js:13306:23)
    at updateChildren (index.js:13233:19)
    at patchVnode (index.js:13306:23)
    at updateChildren (index.js:13233:19)

**Comment by cycleccc** [comment]
这个是 WebView2 + 输入法的特定环境问题，和普通 Edge 页面不是同一个运行条件。

建议把它按 `WebView2` / `输入法` 场景单独跟踪（不要和普通浏览器问题混在一起）。

这类问题定位时至少要带上：
- WebView2 Runtime 版本
- 输入法版本
- 可复现最小页面

没有这三个信息很难稳定定位。
