### ISSUE TITLE
上传图片的时候选择自定义上传customUpload，图片是上传成功并返回路径了，但insertFn报错了

### ISSUE THREAD

**Issue by didikanbudong** [wangeditor-team/wangEditor#6008]
## 问题描述

上传图片的时候选择自定义上传customUpload，图片是上传成功并返回路径了，但insertFn报错了，报错内容：
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'replace')
    at a$ (index.esm.js:15:26215)
    at index.esm.js:15:40046
    at index.esm.js:15:1785
    at Object.next (index.esm.js:15:1886)
    at a2 (index.esm.js:15:628)

## wangEditor 版本
"@wangeditor/editor": "^5.1.23",
    "@wangeditor/editor-for-vue": "^5.1.12",

## 是否查阅了文档 ？
是

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by dai-shifu** [comment]
提供一下关键代码。
比如   uploadImage 配置 ,   res 返参的格式。
```
type InsertFnType = (url: string, alt: string, href: string) => void;
/**
 * 编辑器图片上传配置
 */
export const uploadImage = {
  server: baseURL + '/api/attachment/upload',
  fieldName: 'file',
  customInsert(res: any, insertFn: InsertFnType) {
    // 从 res 中找到 url alt href ，然后插入图片
    const { attachmentUrl: url, attachmentName: alt } = res.data || {};

    // console.log('imageRes',res)
    insertFn(url, alt, '');
  },
};
```

**Comment by cycleccc** [comment]
如果你走的是自定义上传，`wangEditor-next` 这边更推荐直接按 `customUpload` / `customInsert` 的约定来接，不要混着依赖默认 response 结构。

参考：
- 上传图片菜单配置
  https://wangeditor-next.github.io/docs/zh/guide/menu-config.html

`wangEditor-next` 里：
- `customUpload(file, insertFn, editor)` 可以自己上传后，直接调用 `insertFn(src, alt, href)`
- 如果服务端返回结构和默认约定不一致，就走 `customInsert(res, insertFn)`

也就是说，这类“上传成功了，但 `insertFn` 时报错”的问题，通常不要再走默认 response 解析，直接在 `customUpload` / `customInsert` 里把最终 `src/alt/href` 明确传给编辑器会更稳。
